### PR TITLE
Rename WorkspaceGroupAccess model

### PR DESCRIPTION
**Pull request by amstilp**
Rename the WorkspaceDataAccess model to WorkspaceDataSharing.

This is more consistent with our and AnVIL's terminology.

### CODE REVIEW

**Comment by amstilp** [comment]
This is currently broken on MySQL due to a bug in Django with migrations. Hopefully it will be fixed in a new 3.2.x release.

**Comment by jmcarson** [comment]
Sounds like this is a known issue? Is there a django ticket number for the bug you are referencing?

**Comment by amstilp** [comment]
Yes, the ticket is found is here: https://code.djangoproject.com/ticket/31335 and I think it's referencing the same issue. Installing Django 3.2.16 doesn't fix it.

**Comment by jmcarson** [comment]
Unlikely this will be fixed in 3.2.* due to lts
I think we could likely manually alter the migration to avoid the issue unless you have other ideas.

**Comment by amstilp** [comment]
I was hoping it would be fixed since it looks like a bug :/ I do not have other ideas, and I haven't altered migrations before.

This branch is also not strictly necessary but it does clear up some terminology.

**Comment by jmcarson** [comment]
@amstilp ok this is good to merge in I think. I tried a few different options but the only one that really worked without too much complexity was keeping the constraint name the same. I added a comment with info on why we did that so future devs do not try to *fix* it. And when the bug fix is available or when we move to 4.1+ and can use RenameConstraint we can fix it.

**Comment by amstilp** [comment]
Thanks! I'll take a closer look at it on Friday and merge it in then.

**Pull request merged**
